#############################################################################
# Makefile for building: myBrew
# Generated by qmake (3.1) (Qt 5.12.4)
# Project:  myBrew.pro
# Template: app
# Command: /usr/bin/qmake-qt5 -o Makefile myBrew.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtPrintSupport -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtSql -isystem /usr/include/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib64/qt5/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake-qt5
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake-qt5 -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake-qt5 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = myBrew1.0.0
DISTDIR = /root/myBrew/.tmp/myBrew1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) /usr/lib64/libQt5PrintSupport.so /usr/lib64/libQt5Widgets.so /usr/lib64/libQt5Gui.so /usr/lib64/libQt5Sql.so /usr/lib64/libQt5Core.so /usr/lib64/libGL.so -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		qcustomplot.cpp \
		SensorWorkerThread.cpp \
		PIDThread.cpp \
		beerxmlrecipe.cpp \
		pugixml.cpp \
		vessel.cpp \
		mlt.cpp \
		kettle.cpp \
		step.cpp \
		hlt.cpp \
		hop.cpp \
		fermentable.cpp \
		brewconstantspopup.cpp \
		brewstepdurationpopup.cpp \
		tempprobecalibrationpopup.cpp \
		hltpidsettingspopup.cpp \
		bkpidsettingspopup.cpp \
		audio_alarmsettingspopup.cpp \
		brewerysettings.cpp moc_mainwindow.cpp \
		moc_qcustomplot.cpp \
		moc_SensorWorkerThread.cpp \
		moc_PIDThread.cpp \
		moc_brewconstantspopup.cpp \
		moc_brewstepdurationpopup.cpp \
		moc_tempprobecalibrationpopup.cpp \
		moc_hltpidsettingspopup.cpp \
		moc_bkpidsettingspopup.cpp \
		moc_audio_alarmsettingspopup.cpp
OBJECTS       = main.o \
		mainwindow.o \
		qcustomplot.o \
		SensorWorkerThread.o \
		PIDThread.o \
		beerxmlrecipe.o \
		pugixml.o \
		vessel.o \
		mlt.o \
		kettle.o \
		step.o \
		hlt.o \
		hop.o \
		fermentable.o \
		brewconstantspopup.o \
		brewstepdurationpopup.o \
		tempprobecalibrationpopup.o \
		hltpidsettingspopup.o \
		bkpidsettingspopup.o \
		audio_alarmsettingspopup.o \
		brewerysettings.o \
		moc_mainwindow.o \
		moc_qcustomplot.o \
		moc_SensorWorkerThread.o \
		moc_PIDThread.o \
		moc_brewconstantspopup.o \
		moc_brewstepdurationpopup.o \
		moc_tempprobecalibrationpopup.o \
		moc_hltpidsettingspopup.o \
		moc_bkpidsettingspopup.o \
		moc_audio_alarmsettingspopup.o
DIST          = /usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/toolchain.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/usr/lib64/qt5/mkspecs/features/qt.prf \
		/usr/lib64/qt5/mkspecs/features/resources.prf \
		/usr/lib64/qt5/mkspecs/features/moc.prf \
		/usr/lib64/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt5/mkspecs/features/uic.prf \
		/usr/lib64/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib64/qt5/mkspecs/features/file_copies.prf \
		/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/usr/lib64/qt5/mkspecs/features/lex.prf \
		myBrew.pro mainwindow.h \
		qcustomplot.h \
		SensorWorkerThread.h \
		PIDThread.h \
		beerxmlrecipe.h \
		pugixml.hpp \
		pugiconfig.hpp \
		vessel.h \
		mlt.h \
		kettle.h \
		defines.h \
		step.h \
		hlt.h \
		hop.h \
		fermentable.h \
		brewconstantspopup.h \
		brewstepdurationpopup.h \
		tempprobecalibrationpopup.h \
		hltpidsettingspopup.h \
		bkpidsettingspopup.h \
		audio_alarmsettingspopup.h \
		brewerysettings.h main.cpp \
		mainwindow.cpp \
		qcustomplot.cpp \
		SensorWorkerThread.cpp \
		PIDThread.cpp \
		beerxmlrecipe.cpp \
		pugixml.cpp \
		vessel.cpp \
		mlt.cpp \
		kettle.cpp \
		step.cpp \
		hlt.cpp \
		hop.cpp \
		fermentable.cpp \
		brewconstantspopup.cpp \
		brewstepdurationpopup.cpp \
		tempprobecalibrationpopup.cpp \
		hltpidsettingspopup.cpp \
		bkpidsettingspopup.cpp \
		audio_alarmsettingspopup.cpp \
		brewerysettings.cpp
QMAKE_TARGET  = myBrew
DESTDIR       = 
TARGET        = myBrew


first: all
####### Build rules

myBrew: ui_mainwindow.h ui_brewconstantspopup.h ui_brewstepdurationpopup.h ui_tempprobecalibrationpopup.h ui_hltpidsettingspopup.h ui_bkpidsettingspopup.h ui_audio_alarmsettingspopup.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: myBrew.pro /usr/lib64/qt5/mkspecs/linux-g++/qmake.conf /usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/toolchain.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/usr/lib64/qt5/mkspecs/features/qt.prf \
		/usr/lib64/qt5/mkspecs/features/resources.prf \
		/usr/lib64/qt5/mkspecs/features/moc.prf \
		/usr/lib64/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt5/mkspecs/features/uic.prf \
		/usr/lib64/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib64/qt5/mkspecs/features/file_copies.prf \
		/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/usr/lib64/qt5/mkspecs/features/lex.prf \
		myBrew.pro
	$(QMAKE) -o Makefile myBrew.pro
/usr/lib64/qt5/mkspecs/features/spec_pre.prf:
/usr/lib64/qt5/mkspecs/common/unix.conf:
/usr/lib64/qt5/mkspecs/common/linux.conf:
/usr/lib64/qt5/mkspecs/common/sanitize.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt5/mkspecs/common/g++-base.conf:
/usr/lib64/qt5/mkspecs/common/g++-unix.conf:
/usr/lib64/qt5/mkspecs/qconfig.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib64/qt5/mkspecs/features/qt_functions.prf:
/usr/lib64/qt5/mkspecs/features/qt_config.prf:
/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib64/qt5/mkspecs/features/spec_post.prf:
/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt5/mkspecs/features/toolchain.prf:
/usr/lib64/qt5/mkspecs/features/default_pre.prf:
/usr/lib64/qt5/mkspecs/features/resolve_config.prf:
/usr/lib64/qt5/mkspecs/features/default_post.prf:
/usr/lib64/qt5/mkspecs/features/warn_on.prf:
/usr/lib64/qt5/mkspecs/features/qt.prf:
/usr/lib64/qt5/mkspecs/features/resources.prf:
/usr/lib64/qt5/mkspecs/features/moc.prf:
/usr/lib64/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib64/qt5/mkspecs/features/uic.prf:
/usr/lib64/qt5/mkspecs/features/unix/thread.prf:
/usr/lib64/qt5/mkspecs/features/qmake_use.prf:
/usr/lib64/qt5/mkspecs/features/file_copies.prf:
/usr/lib64/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib64/qt5/mkspecs/features/exceptions.prf:
/usr/lib64/qt5/mkspecs/features/yacc.prf:
/usr/lib64/qt5/mkspecs/features/lex.prf:
myBrew.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile myBrew.pro

qmake_all: FORCE


all: Makefile myBrew

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib64/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h qcustomplot.h SensorWorkerThread.h PIDThread.h beerxmlrecipe.h pugixml.hpp pugiconfig.hpp vessel.h mlt.h kettle.h defines.h step.h hlt.h hop.h fermentable.h brewconstantspopup.h brewstepdurationpopup.h tempprobecalibrationpopup.h hltpidsettingspopup.h bkpidsettingspopup.h audio_alarmsettingspopup.h brewerysettings.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp qcustomplot.cpp SensorWorkerThread.cpp PIDThread.cpp beerxmlrecipe.cpp pugixml.cpp vessel.cpp mlt.cpp kettle.cpp step.cpp hlt.cpp hop.cpp fermentable.cpp brewconstantspopup.cpp brewstepdurationpopup.cpp tempprobecalibrationpopup.cpp hltpidsettingspopup.cpp bkpidsettingspopup.cpp audio_alarmsettingspopup.cpp brewerysettings.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.ui brewconstantspopup.ui brewstepdurationpopup.ui tempprobecalibrationpopup.ui hltpidsettingspopup.ui bkpidsettingspopup.ui audio_alarmsettingspopup.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib64/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -W -dM -E -o moc_predefs.h /usr/lib64/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_qcustomplot.cpp moc_SensorWorkerThread.cpp moc_PIDThread.cpp moc_brewconstantspopup.cpp moc_brewstepdurationpopup.cpp moc_tempprobecalibrationpopup.cpp moc_hltpidsettingspopup.cpp moc_bkpidsettingspopup.cpp moc_audio_alarmsettingspopup.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_qcustomplot.cpp moc_SensorWorkerThread.cpp moc_PIDThread.cpp moc_brewconstantspopup.cpp moc_brewstepdurationpopup.cpp moc_tempprobecalibrationpopup.cpp moc_hltpidsettingspopup.cpp moc_bkpidsettingspopup.cpp moc_audio_alarmsettingspopup.cpp
moc_mainwindow.cpp: mainwindow.h \
		SensorWorkerThread.h \
		PIDThread.h \
		qcustomplot.h \
		beerxmlrecipe.h \
		pugixml.hpp \
		pugiconfig.hpp \
		step.h \
		defines.h \
		vessel.h \
		hlt.h \
		mlt.h \
		kettle.h \
		hop.h \
		fermentable.h \
		brewconstantspopup.h \
		brewstepdurationpopup.h \
		tempprobecalibrationpopup.h \
		bkpidsettingspopup.h \
		hltpidsettingspopup.h \
		audio_alarmsettingspopup.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /root/myBrew/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/root/myBrew -I/usr/include/qt5 -I/usr/include/qt5/QtPrintSupport -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtSql -I/usr/include/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/c++/9/x86_64-redhat-linux -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-redhat-linux/9/include -I/usr/local/include -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_qcustomplot.cpp: qcustomplot.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /root/myBrew/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/root/myBrew -I/usr/include/qt5 -I/usr/include/qt5/QtPrintSupport -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtSql -I/usr/include/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/c++/9/x86_64-redhat-linux -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-redhat-linux/9/include -I/usr/local/include -I/usr/include qcustomplot.h -o moc_qcustomplot.cpp

moc_SensorWorkerThread.cpp: SensorWorkerThread.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /root/myBrew/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/root/myBrew -I/usr/include/qt5 -I/usr/include/qt5/QtPrintSupport -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtSql -I/usr/include/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/c++/9/x86_64-redhat-linux -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-redhat-linux/9/include -I/usr/local/include -I/usr/include SensorWorkerThread.h -o moc_SensorWorkerThread.cpp

moc_PIDThread.cpp: PIDThread.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /root/myBrew/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/root/myBrew -I/usr/include/qt5 -I/usr/include/qt5/QtPrintSupport -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtSql -I/usr/include/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/c++/9/x86_64-redhat-linux -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-redhat-linux/9/include -I/usr/local/include -I/usr/include PIDThread.h -o moc_PIDThread.cpp

moc_brewconstantspopup.cpp: brewconstantspopup.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /root/myBrew/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/root/myBrew -I/usr/include/qt5 -I/usr/include/qt5/QtPrintSupport -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtSql -I/usr/include/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/c++/9/x86_64-redhat-linux -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-redhat-linux/9/include -I/usr/local/include -I/usr/include brewconstantspopup.h -o moc_brewconstantspopup.cpp

moc_brewstepdurationpopup.cpp: brewstepdurationpopup.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /root/myBrew/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/root/myBrew -I/usr/include/qt5 -I/usr/include/qt5/QtPrintSupport -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtSql -I/usr/include/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/c++/9/x86_64-redhat-linux -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-redhat-linux/9/include -I/usr/local/include -I/usr/include brewstepdurationpopup.h -o moc_brewstepdurationpopup.cpp

moc_tempprobecalibrationpopup.cpp: tempprobecalibrationpopup.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /root/myBrew/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/root/myBrew -I/usr/include/qt5 -I/usr/include/qt5/QtPrintSupport -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtSql -I/usr/include/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/c++/9/x86_64-redhat-linux -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-redhat-linux/9/include -I/usr/local/include -I/usr/include tempprobecalibrationpopup.h -o moc_tempprobecalibrationpopup.cpp

moc_hltpidsettingspopup.cpp: hltpidsettingspopup.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /root/myBrew/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/root/myBrew -I/usr/include/qt5 -I/usr/include/qt5/QtPrintSupport -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtSql -I/usr/include/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/c++/9/x86_64-redhat-linux -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-redhat-linux/9/include -I/usr/local/include -I/usr/include hltpidsettingspopup.h -o moc_hltpidsettingspopup.cpp

moc_bkpidsettingspopup.cpp: bkpidsettingspopup.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /root/myBrew/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/root/myBrew -I/usr/include/qt5 -I/usr/include/qt5/QtPrintSupport -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtSql -I/usr/include/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/c++/9/x86_64-redhat-linux -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-redhat-linux/9/include -I/usr/local/include -I/usr/include bkpidsettingspopup.h -o moc_bkpidsettingspopup.cpp

moc_audio_alarmsettingspopup.cpp: audio_alarmsettingspopup.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /root/myBrew/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/root/myBrew -I/usr/include/qt5 -I/usr/include/qt5/QtPrintSupport -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtSql -I/usr/include/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/c++/9/x86_64-redhat-linux -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-redhat-linux/9/include -I/usr/local/include -I/usr/include audio_alarmsettingspopup.h -o moc_audio_alarmsettingspopup.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_brewconstantspopup.h ui_brewstepdurationpopup.h ui_tempprobecalibrationpopup.h ui_hltpidsettingspopup.h ui_bkpidsettingspopup.h ui_audio_alarmsettingspopup.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_brewconstantspopup.h ui_brewstepdurationpopup.h ui_tempprobecalibrationpopup.h ui_hltpidsettingspopup.h ui_bkpidsettingspopup.h ui_audio_alarmsettingspopup.h
ui_mainwindow.h: mainwindow.ui \
		/usr/lib64/qt5/bin/uic \
		qcustomplot.h
	/usr/lib64/qt5/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_brewconstantspopup.h: brewconstantspopup.ui \
		/usr/lib64/qt5/bin/uic
	/usr/lib64/qt5/bin/uic brewconstantspopup.ui -o ui_brewconstantspopup.h

ui_brewstepdurationpopup.h: brewstepdurationpopup.ui \
		/usr/lib64/qt5/bin/uic
	/usr/lib64/qt5/bin/uic brewstepdurationpopup.ui -o ui_brewstepdurationpopup.h

ui_tempprobecalibrationpopup.h: tempprobecalibrationpopup.ui \
		/usr/lib64/qt5/bin/uic
	/usr/lib64/qt5/bin/uic tempprobecalibrationpopup.ui -o ui_tempprobecalibrationpopup.h

ui_hltpidsettingspopup.h: hltpidsettingspopup.ui \
		/usr/lib64/qt5/bin/uic
	/usr/lib64/qt5/bin/uic hltpidsettingspopup.ui -o ui_hltpidsettingspopup.h

ui_bkpidsettingspopup.h: bkpidsettingspopup.ui \
		/usr/lib64/qt5/bin/uic
	/usr/lib64/qt5/bin/uic bkpidsettingspopup.ui -o ui_bkpidsettingspopup.h

ui_audio_alarmsettingspopup.h: audio_alarmsettingspopup.ui \
		/usr/lib64/qt5/bin/uic
	/usr/lib64/qt5/bin/uic audio_alarmsettingspopup.ui -o ui_audio_alarmsettingspopup.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		SensorWorkerThread.h \
		PIDThread.h \
		qcustomplot.h \
		beerxmlrecipe.h \
		pugixml.hpp \
		pugiconfig.hpp \
		step.h \
		defines.h \
		vessel.h \
		hlt.h \
		mlt.h \
		kettle.h \
		hop.h \
		fermentable.h \
		brewconstantspopup.h \
		brewstepdurationpopup.h \
		tempprobecalibrationpopup.h \
		bkpidsettingspopup.h \
		hltpidsettingspopup.h \
		audio_alarmsettingspopup.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		SensorWorkerThread.h \
		PIDThread.h \
		qcustomplot.h \
		beerxmlrecipe.h \
		pugixml.hpp \
		pugiconfig.hpp \
		step.h \
		defines.h \
		vessel.h \
		hlt.h \
		mlt.h \
		kettle.h \
		hop.h \
		fermentable.h \
		brewconstantspopup.h \
		brewstepdurationpopup.h \
		tempprobecalibrationpopup.h \
		bkpidsettingspopup.h \
		hltpidsettingspopup.h \
		audio_alarmsettingspopup.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

qcustomplot.o: qcustomplot.cpp qcustomplot.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qcustomplot.o qcustomplot.cpp

SensorWorkerThread.o: SensorWorkerThread.cpp SensorWorkerThread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SensorWorkerThread.o SensorWorkerThread.cpp

PIDThread.o: PIDThread.cpp PIDThread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o PIDThread.o PIDThread.cpp

beerxmlrecipe.o: beerxmlrecipe.cpp beerxmlrecipe.h \
		pugixml.hpp \
		pugiconfig.hpp \
		step.h \
		defines.h \
		vessel.h \
		hlt.h \
		mlt.h \
		kettle.h \
		hop.h \
		fermentable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o beerxmlrecipe.o beerxmlrecipe.cpp

pugixml.o: pugixml.cpp pugixml.hpp \
		pugiconfig.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pugixml.o pugixml.cpp

vessel.o: vessel.cpp vessel.h \
		step.h \
		defines.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vessel.o vessel.cpp

mlt.o: mlt.cpp mlt.h \
		defines.h \
		vessel.h \
		step.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mlt.o mlt.cpp

kettle.o: kettle.cpp kettle.h \
		defines.h \
		vessel.h \
		step.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o kettle.o kettle.cpp

step.o: step.cpp step.h \
		defines.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o step.o step.cpp

hlt.o: hlt.cpp defines.h \
		hlt.h \
		vessel.h \
		step.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hlt.o hlt.cpp

hop.o: hop.cpp hop.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hop.o hop.cpp

fermentable.o: fermentable.cpp fermentable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fermentable.o fermentable.cpp

brewconstantspopup.o: brewconstantspopup.cpp brewconstantspopup.h \
		ui_brewconstantspopup.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o brewconstantspopup.o brewconstantspopup.cpp

brewstepdurationpopup.o: brewstepdurationpopup.cpp brewstepdurationpopup.h \
		ui_brewstepdurationpopup.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o brewstepdurationpopup.o brewstepdurationpopup.cpp

tempprobecalibrationpopup.o: tempprobecalibrationpopup.cpp tempprobecalibrationpopup.h \
		ui_tempprobecalibrationpopup.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tempprobecalibrationpopup.o tempprobecalibrationpopup.cpp

hltpidsettingspopup.o: hltpidsettingspopup.cpp hltpidsettingspopup.h \
		ui_hltpidsettingspopup.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hltpidsettingspopup.o hltpidsettingspopup.cpp

bkpidsettingspopup.o: bkpidsettingspopup.cpp bkpidsettingspopup.h \
		ui_bkpidsettingspopup.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bkpidsettingspopup.o bkpidsettingspopup.cpp

audio_alarmsettingspopup.o: audio_alarmsettingspopup.cpp audio_alarmsettingspopup.h \
		ui_audio_alarmsettingspopup.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o audio_alarmsettingspopup.o audio_alarmsettingspopup.cpp

brewerysettings.o: brewerysettings.cpp brewerysettings.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o brewerysettings.o brewerysettings.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_qcustomplot.o: moc_qcustomplot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qcustomplot.o moc_qcustomplot.cpp

moc_SensorWorkerThread.o: moc_SensorWorkerThread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SensorWorkerThread.o moc_SensorWorkerThread.cpp

moc_PIDThread.o: moc_PIDThread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_PIDThread.o moc_PIDThread.cpp

moc_brewconstantspopup.o: moc_brewconstantspopup.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_brewconstantspopup.o moc_brewconstantspopup.cpp

moc_brewstepdurationpopup.o: moc_brewstepdurationpopup.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_brewstepdurationpopup.o moc_brewstepdurationpopup.cpp

moc_tempprobecalibrationpopup.o: moc_tempprobecalibrationpopup.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tempprobecalibrationpopup.o moc_tempprobecalibrationpopup.cpp

moc_hltpidsettingspopup.o: moc_hltpidsettingspopup.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_hltpidsettingspopup.o moc_hltpidsettingspopup.cpp

moc_bkpidsettingspopup.o: moc_bkpidsettingspopup.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_bkpidsettingspopup.o moc_bkpidsettingspopup.cpp

moc_audio_alarmsettingspopup.o: moc_audio_alarmsettingspopup.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_audio_alarmsettingspopup.o moc_audio_alarmsettingspopup.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

